### ISSUE TITLE
Duplicate Symbol Definitions for `setbestsrc`

### ISSUE THREAD

**Issue by mandli** [clawpack/geoclaw#139]
New functionality in AMRClaw that includes gauge output I think has broken GeoClaw.  The `gauge_module` in AMRClaw now includes the `setbestsrc` subroutine as does `dumpgauge.f` so a conflict emerges when `use gauge_module` is done in `setbestsrc` in GeoClaw.  Relevant compile time error:
```
clawpack/geoclaw/src/2d/shallow/dumpgauge.f:140.9:

      use gauges_module                                                 
         1
Error: 'setbestsrc' of module 'gauges_module', imported at (1), is also the name of the current program unit
make: *** [/clawpack/geoclaw/src/2d/shallow/dumpgauge.o] Error 1
make: *** [new] Error 2
```
If `setbestsrc` is commented out in GeoClaw then we also have a problem since `tick` uses this and does not include the `gauge_module` so we arrive at undefined symbols
```
Undefined symbols for architecture x86_64:
  "_setbestsrc_", referenced from:
      _tick_ in tick.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [xgeoclaw] Error 1
```
So the solution is probably just to insert a `use gauge_module, only: setbestsrc` in `tick` or something similar and remove `setbestsrc` from `dumpgauge.f`.

**Comment by rjleveque** [comment]
The `setbestsrc` routine in the new `gauges_module.f90` is not the same as in the old `dumpgauge`, so instead see #140.
