### ISSUE TITLE
Input needed for NSF proposal

### ISSUE THREAD

**Issue by rjleveque** [clawpack/geoclaw#158]
Several of us are putting together an NSF proposal for a Scientific Software Integration (SSI) grant in hopes of getting funding for several years of focused GeoClaw development, developers' workshops, users' workshops, training sessions, documentation, etc. 

We would like to collect information about current and past use of GeoClaw (particularly citations), development work going on that we may be unaware of, requests for new features, or other suggestions.

An email will soon be sent to https://groups.google.com/forum/#!forum/claw-users with more details.  You are welcome to respond by email.

This issue is open for those who wish to post responses here to publicize their activities, or who simply find this more convenient than email.

**Comment by mandli** [comment]
NSF proposal submitted!  Maybe we should open a persistent issue for this though?
