### ISSUE TITLE
gauges.data

### ISSUE THREAD

**Issue by mjberger** [clawpack/geoclaw#175]
we have it in two places - the top directory, and the _output file. The plotting programs use the gauges.data in the top one, and the fort.gauges output from the _output dir.  I suggest it be changed to use the _output only directory for both files, so that new runs with different gauges can be done at the same time as plotting.  why do we even need it in the top dir?

**Comment by mandli** [comment]
I think this actually belongs in visclaw as that's where the gauges are plotted.
