### ISSUE TITLE
Error in plot function in topotools.py for dry topography data

### ISSUE THREAD

**Issue by jgalazm** [clawpack/geoclaw#198]
When the minimum value of the topography is 0 and trying to generate a plot using the topotools.py plot function it raises many errors from matplotlib plotting functions.

I think this behavior is caused by the strict inequality in line 1003 of file geoclaw/src/python/geoclaw/topotools.py:

`if topo_extent[0] > 0.0:`
`  cmap = land_cmap`
`   norm = colors.Normalize(vmin=0.0, vmax=topo_extent[1])`

The fix should be simple by changing ">" with ">=".

You can see an example of what I described in this jupyter notebook

 http://nbviewer.jupyter.org/gist/jgalazm/6cfd1bf5c7382ec8c6d1?flush_cache=true

Cheers.

**Comment by mandli** [comment]
Good catch!  Interesting that the second if clause includes the `=`.  

@jgalazm do you want to issue a PR for the fix?  Otherwise I can make a quick PR.

**Comment by jgalazm** [comment]
Yes sure, I can do that.

**Comment by mandli** [comment]
Addressed by #200.
