### ISSUE TITLE
varying Manning's coefficient in space

### ISSUE THREAD

**Issue by xinshengqin** [clawpack/geoclaw#217]
Recently I found a paper discussing about using different Manning's coefficient for different area in a tsunami inundation model. For instance, a Manning’s coefficient value of 0.035 may be appropriate in the sea, 0.060 on land, and 0.2–1.0 for the area of buildings across the bathymetry. Is it possible to do this in GeoClaw?

Reference:
Ozer Sozdinler, C., Yalciner, A.C., Zaytsev, A., 2015. Investigation of Tsunami Hydrodynamic Parameters in Inundation Zones with Different Structural Layouts. Pure Appl. Geophys. 172, 931–952.

**Comment by rjleveque** [comment]
You can specify a set of Manning coefficients that are used for different ranges of topo elevation, see
  http://www.clawpack.org/setrun_geoclaw.html?highlight=manning_coefficient

I believe @mandli is working on a version that allows specifying a spatially-varying Manning coefficient more generally.

**Comment by mandli** [comment]
Just as a confirmation, we are working on this.  For what you suggested though you may be able to use what @rjleveque pointed to given you want to have regional support.  What we are implementing would be able to take in a field of values similar to how topography is used.

**Comment by xinshengqin** [comment]
I see. Thanks! I think what Randy suggested is good for me for now.
