### ISSUE TITLE
BowlSloshTest fails when run locally

### ISSUE THREAD

**Issue by mandli** [clawpack/geoclaw#246]
When the bowl-slosh test is run from within the directory it is defined in the following error occurs
```
======================================================================
ERROR: runTest (__main__.BowlSloshTest)
Test bowl-slosh example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "regression_tests.py", line 40, in setUp
    from . import make_fgmax_grid
ValueError: Attempted relative import in non-package

----------------------------------------------------------------------
Ran 1 test in 21.782s

FAILED (errors=1)
```
My initial assumption is this due to recent work to be compatible with Python 3 but I have not deeply thought on this yet.  The main reason that we need to make sure this works is that regeneration of testing data is dependent on being able to run the tests from within these directories.

**Comment by rjleveque** [comment]
As far as I know this is no longer a problem.
