### ISSUE TITLE
examples/storm-surge/ike plots

### ISSUE THREAD

**Issue by rjleveque** [clawpack/geoclaw#269]
@mandli:

In this example, the plotting dies in Python3 with an error in `colorbar`.  I haven't investigated further yet.

In Python2 it plots but looks different than what's in the gallery, e.g. the figure below instead of http://www.clawpack.org/gallery/_static/geoclaw/examples/storm-surge/ike/_plots/frame0012fig5.html
Is this expected?

Also, can we remove `plt.hold` calls?

![frame0012fig5](https://user-images.githubusercontent.com/720122/27145369-64aaa55e-50ea-11e7-9212-cb0d403ba647.png)

**Comment by mandli** [comment]
Ah, I know what happened.  There was a bug fix to the computation of the land fall time but that was not corrected in the example itself.  I will issue a PR for that.

I am not certain why this would die at the colorbar call though.  Did you get any indication as to why it died there?

We should remove the hold calls although @hudaquresh just found the same problem as with #268.

**Comment by rjleveque** [comment]
Also, I just noticed you set a bunch of `matplotlib.rcParams` in this `setplot.py`, which means if you cd to a different example you get unexpected behavior unless you restart IPython.  Why do it this way?

I'll investigate colorbar more...

**Comment by mandli** [comment]
I was under the perhaps mistaken impression that for many of these parameters that this was the only way to set these parameters.  Honestly those can be removed from the examples anyway given that they were a hold over from a paper and can be kept in the surge-examples apps repository.

**Comment by rjleveque** [comment]
I think the colorbar problem arises from line 319 of `frametools.py`, where `plotitem._current_pobj` returns `None` instead of a plot object.  Stopping at line 329 with pdb shows this, not clear why there's a problem...

```
(Pdb) plotitem._current_pobj
(Pdb) plotitem.name
'surface'
(Pdb) plotitem.plot_type
'2d_contourf'
(Pdb) plotitem.plot_var
<function surface_or_depth at 0x11f0168c8>
(Pdb) plotitem.data_show
True

``

**Comment by rjleveque** [comment]
I think all these `rcParams` can be set directly within commands like `plot`, `legend`, `xticks`, etc.

**Comment by rjleveque** [comment]
@mandli: There's a lot of stuff in this `setplot.py` that seems to be specific to an article and/or commented out. Maybe clean it up and then we'll see if the colorbar still gives problems?

**Comment by mandli** [comment]
#270 I am hoping fixes most of the issues reported.  Let me know if it's still not up to snuff.
