### ISSUE TITLE
Vmax in holland wind profile

### ISSUE THREAD

**Issue by bolliger32** [clawpack/geoclaw#413]
@mandli should the max wind speed used in the holland1980 wind profile be using the modified Vmax (adjusting to the top of the boundary layer and removing translational speed) instead of the raw Vmax?

i.e. in lines 470-472 of `model_storm_module.f90`, should `mws` be `mws_mod`?
```
                ! Speed of wind at this point
                wind = sqrt((mwr / r)**B &
                        * exp(1.d0 - (mwr / r)**B) * mws**2.d0 &
                        + (r * f)**2.d0 / 4.d0) - r * f / 2.d0
```

**Comment by mandli** [comment]
Good question.  The original source code is from ADCIRC's implementation of the Holland 1980 field.  Looking back at the original code it looks like the `mws` is the parameter used in the wind.
