### ISSUE TITLE
Handling of NaNs in radius_wind_max interpolation

### ISSUE THREAD

**Issue by tovogt** [clawpack/geoclaw#430]
There's a Python utility function in `geoclaw.surge.storm` called `fill_rad_w_other_source` that helps in filling missing wind radius data from storm track information. One ingredient is an interpolation step in

https://github.com/clawpack/geoclaw/blob/8ff1c6fd47b4075e9cda4e8479e212769781644f/src/python/geoclaw/surge/storm.py#L1391

However, at the point of calling xarray's `interp`, the dataset might still contain NaNs. Now, according to the docs for `scipy.interpolate.interp1d` (which is used internally by xarray), "calling `interp1d` with NaNs present in input values results in undefined behaviour" ([source](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d)).

I suggest adding `fill_da = fill_da.dropna('t')` before calling `interp`.

In a side note, it would come in handy to pass keyword arguments to the call of `interp1d` using xarray's `kwargs` argument. In my application, it's for `fill_value='extrapolate'`.

**Comment by mandli** [comment]
This makes sense.  We generally try to have a default value for storm radius but this really does not work well either.  If you can issue a PR for this we would be grateful.

**Comment by tovogt** [comment]
See #432 for the PR.
