### ISSUE TITLE
Some errors in wind field models

### ISSUE THREAD

**Issue by bolliger32** [clawpack/geoclaw#466]
As I was creating #467, I noticed that a couple of the wind field models seem to have errors in them:

- The CLE model calculates the circular windspeed by removing the translational wind speed, but then does not use it anywhere in the model. I'm not sure if CLE is supposed to be using the circular wind speed in the algorithms it implements, but I think so?
- The Willoughby field has this weird clause at the bottom:
```
                ! Speed of wind at this point
                if (r < 0.9d0 * mwr) then 
                    wind = mws * (r / mwr)**0.45d0
                !else if (r > 0.9d0 * mwr & r < 1.1d0 * mwr) then 
                else if (r > 0.9d0) then 
                    wind = 2.d0 
                else 
                    wind = 1.d0 
                end if  
```
Seems like there are some bugs to fix there.

Once these bugs are addressed, there should probably be a regression test for each wind field. I didn't look at any of the other wind fields in depth but just noticed those that I mentioned. Might be worth a detailed look.

**Comment by mandli** [comment]
@hudaquresh can you take a look at this?
