### ISSUE TITLE
Too many values in call to preintcopy within filval.f90

### ISSUE THREAD

**Issue by bolliger32** [clawpack/geoclaw#476]
No idea why this hasn't occurred until now but I just tried to compile geoclaw on a new machine (perhaps the clang compiler was different or i used different flags) and I was getting an type error on this line:

https://github.com/clawpack/geoclaw/blob/b453dbd735df50a9c8c2fe6f0e91337e460501f4/src/2d/shallow/filval.f90#L154

I'm pretty sure there are too many arguments for the actual [preintcopy](https://github.com/clawpack/amrclaw/blob/master/src/2d/preintcopy.f) subroutine in amrclaw. I deleted the two "1"s toward the end of the arguments and it compiled fine, but I wanted to check that this was actually correct before I filed a PR. I don't actually know anything about this subroutine.

Here's the error I was getting:
```
gfortran -c -cpp /Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/valout.f90 					  -I/Users/ianbolliger/git_repos/clawpack/amrclaw/src/2d/ -I/Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/ -I/Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/multilayer/ -I/Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/surge/ -L/Users/ianbolliger/Desktop/test_simple-run_emanuel_run_emcurrent/    -o /Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/valout.o
gfortran -c -cpp filval.f90 					  -I/Users/ianbolliger/git_repos/clawpack/amrclaw/src/2d/ -I/Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/ -I/Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/multilayer/ -I/Users/ianbolliger/git_repos/clawpack/geoclaw/src/2d/shallow/surge/ -L/Users/ianbolliger/Desktop/test_simple-run_emanuel_run_emcurrent/    -o filval.o
filval.f90:154:37:

   95 | call preintcopy(valc,mic,mjc,nvar,iclo,ichi,jclo,jchi,level-1,fliparray)
      |                                                              2
......
  154 |          jlo-nghost,jhi+nghost,level,1,1,fliparray)
      |                                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
```

**Comment by mandli** [comment]
Given that we usually do not do periodic domains in GeoClaw.  Given that these arguments are missing in the corresponding `filval.f90` in AMRClaw I would say this is probably the right change.  @mjberger did we miss this when fixing periodic BCs in GeoClaw a while ago?

**Comment by mjberger** [comment]
I will have to look.

It's missing in filial because of the periodicity that the "pre" routines take care of.

I'll get on it today.

 — Marsha

**Comment by mjberger** [comment]
looks like you're right.  Change did not propagate to GeoClaw.  Luckily there's only the one call.
So your fix is good.

Thanks,
 — Marsha

**Comment by rjleveque** [comment]
I'm about to announce the release of v5.7.1, which is already finalized, but we should include this along with some other GeoClaw bug fixes that we're saving for v5.8.0.  Which will appear soon I hope.

**Comment by bolliger32** [comment]
Sounds good! I'll file a PR with this little change now

**Comment by mjberger** [comment]
None of our tests would have caught this. We need to make up a periodic test for GeoClaw, 
maybe all around the equator with a strip in the other direction.  

Should we put it on the list for the next hackathon?

 — Marsha

**Comment by mandli** [comment]
I have something similar when I was doing global simulations if you want me to dig that one up and added it to tests.  Otherwise it might be a good example to put in the surge repository too as it could be a could demo of the ensemble of storms capability.
