### ISSUE TITLE
[Question] Difference between rho in different places

### ISSUE THREAD

**Issue by piyueh** [clawpack/geoclaw#497]
Hi, just out of curiosity: what's the difference in the meanings of the `rho`s in `src2.f90` and `geoclaw_module.f90`?

`src2.f90`:
https://github.com/clawpack/geoclaw/blob/6adc6e29d541c0813db0341b09977b0287b8d442/src/2d/shallow/src2.f90#L42

`geoclaw_module.f90`:
https://github.com/clawpack/geoclaw/blob/6adc6e29d541c0813db0341b09977b0287b8d442/src/2d/shallow/geoclaw_module.f90#L32

**Comment by mandli** [comment]
Technically speaking these should be the same.  The fact that there are multiple values allowed in `geoclaw_mdoule.f90` is due to the multi-layer capabilities.  What should be corrected is that the `rho` in `src2` should take the value from `rho(1)` in `geoclaw_module`.

**Comment by piyueh** [comment]
Got it! Thanks!
