### ISSUE TITLE
Non-hydrostatic tsunami modeling

### ISSUE THREAD

**Issue by Thomas-Ulrich** [clawpack/geoclaw#501]
Hi,

For those who did not read my previous issue:
I m Thomas Ulrich, a Postdoc from LMU, Munich.
I'm trying to set up a tsunami simulation of the Sumatra 2004 earthquake, with initial displacement from a 3d dynamic rupture model (Actually, I already run tsunami simulations for this earthquake using Samoa, a code developed by TUM, but I would like to account also for non-hydrostatic gradient, which Samoa does not support actually).
At this stage, I think I was able to run a shallow water simulation with geoclaw and the results look very similar to what I was getting with Samoa.

1) creating the surface2d plots is rather slow when simulation resolution is high

_output is 14Gb (which does not seem very large for 30 snapshots, ascii), I have 4 levels of refinement.
```
    clawdata.num_cells[0] = 53*2
    clawdata.num_cells[1] = 44*2
    amrdata.amr_levels_max = 4
    # List of refinement ratios at each level (length at least mxnest-1)
    amrdata.refinement_ratios_x = [4,4,2]
    amrdata.refinement_ratios_y = [4,4,2]
    amrdata.refinement_ratios_t = [4,4,2]
```
Any idea to speed that up? (e.g. xdmf output to be read in paraview?).

(and sorry for putting 2 issues in one)
2) I would like to account now for the 'non-hydrostatic gradient' in my simulation.

Indeed, the use of non-hydrostatic (distributed) models may improve the agreement between the observation and simulations, in terms of timing (so said one of the reviewers of our paper about Sumatra). Is there some existing setup that I could use to set up my simulation based on the shallow water simulation?
Some papers I need to read?
Thx in advance.

Thomas.

**Comment by mandli** [comment]
Just to clarify your issues here:
1. You want to speed up the plotting, for instance using paraview?
2. You would like to include non-hydrostatic components in GeoClaw simulations or just understand where they might make an estimate after the fact?

**Comment by Thomas-Ulrich** [comment]
Hi,
Thx for yout quick answer.

1. yes, with paraview, or with the build-in plotter (maybe there are some tips and tricks I m not aware of). 
I've been producing about 10 frames in more than 2 hours 30 (1/3 of the surface outputs), while the simulation itself took less than 1h.

2.Yes I would like to include non-hydrostatic components in GeoClaw simulation.

**Comment by Thomas-Ulrich** [comment]
Do I understand correctly that 2. could be enabled using the 2d simulation of https://github.com/mandli/multilayer-examples as a start point?

**Comment by Thomas-Ulrich** [comment]
Hi,
about 1., I think I figured it out: if I remove all patch edges and cell edges, I get one frame done in about 25s (about 15s for reading the data. probably if the data were binary, it would have been even faster).
So I should have my 30 frames in half an hour which is ok.
That solves half the issue ;-)

**Comment by Thomas-Ulrich** [comment]
Hi again,
So I also found the BoussClaw repository and got the Bowl2d running.
I will try to adapt my Sumatra simulation to it. 
Can you confirm that BoussClaw is what I was looking for?
Thx,
Thomas.

**Comment by rjleveque** [comment]
Hi Thomas,

Regarding plotting, turning off plotting of the cell and patch edges is
definitely a good idea and with lots of fine grids these would totally
obscure the simulation results anyway.  You can also turn off plotting all
data at some level(s) by specifying
   plotitem.amr_data_show = [1,1,0]
for example if you only want to plot level 1 and 2 data for some item (e.g.
a zoomed out view where you're not resolving the coastal regions where you
have fine grids).

Also you should check that you have set
   plotdata.parallel = True
in order to plot multiple frames in parallel (using OMP_NUM_THREADS to
specify the number of threads to use).

Regarding BoussClaw, I think the version you found is the one developed
primarily by Jihwan Kim to implement Boussinesq equations, as described in this
paper <http://faculty.washington.edu/rjl/pubs/bouss2017/index.html>.  That
version may work for you, but it only worked on a single grid, not with
AMR.  Also, more recently we've discovered some other issues with it, and
I've been working with Marsha Berger on a new version that also supports
AMR.  This is a bit tricky since the higher-order dispersive terms require
implicit solvers.  We're struggling with some stability issues at the
moment but hope to have something more robust available in the future. Not
sure of the time scale for that right now.

 - Randy

**Comment by donnaaboise** [comment]
If what you are interested in is really solving Boussinesq/Serre-Green-Naghdi equations, we have a version just now working in ForestClaw, if you'd like to try that out.  We would love a beta tester.

**Comment by Thomas-Ulrich** [comment]
Hi,
Thx @rjleveque, I missed the plotdata.parallel = True option, that's good to know!
About the Non-hydrostatic tsunami modeling simulation, what I m interested in is to capture more properly the dispersivity of the tsunami waves in the Indian Ocean. In fact, the tsunami from our 3d dynamic rupture source is slightly inconsistent in terms of the timing of the first waves, compared to the Jason satellite transect (but well we used so far a cartesian grid, which is quite deformed because centered on the source). The use of a non-hydrostatic tsunami model is suggested by one reviewer of our paper (preprint here https://osf.io/9kdhb).

So in the end, what I need is a tsunami code that can handle both earth sphericity and account for a non-hydrostatic gradient.
And all of that should work out of the box given the short timing granted for the review...
@donnaaboise does ForestClaw could meet these requirements? (I m ok to test the code)

In the end, global non-hydrostatic tsunami modeling simulation may be beyond the state of the art (while It seems some code, e.g. Funwave-tvd may allow doing that to some extent (I read Funwave-TVD can do weakly non-linear)), and the reviewer may have been over-optimistic.

Thomas.

**Comment by donnaaboise** [comment]
It would quite a lot from the reviewer to expect that you can just "include dispersive terms" - that is a non-trivial task!   So probably the turn around time for a review is really too short to do a reasonable job.  In any case, the ForestClaw Serre-Green-Naghdi (SGN) solver doesn't yet have support for lat/long coordinates, and that would take time to develop and test.

**Comment by Thomas-Ulrich** [comment]
Thank you for your opinion on that.
That was also my impression, but I m a seismologist, so I could not be sure I m right.
Anyway, I m happy I could test geoclaw. It so fast, and the numerical dispersion seems very limited!
And I will be happy to test your code, once you have integrated the planned development.
Thomas.
