### ISSUE TITLE
TCs in GeoClaw always rotate counterclockwise?

### ISSUE THREAD

**Issue by tovogt** [clawpack/geoclaw#514]
From running a toy example on the southern hemisphere I noticed that GeoClaw's wind field models seem to generate tropical cyclones with counterclockwise rotation regardless of hemisphere, even though rotation should be clockwise on the southern hemisphere. Can you confirm this?

**Comment by mandli** [comment]
Oh, that is completely true.  Definitely a bug.

**Comment by mandli** [comment]
Fixed by #519.
