### ISSUE TITLE
FileNotFoundError etopo10min120W60W60S0S.asc in geoclaw/examples/tsunami/chile2010

### ISSUE THREAD

**Issue by fabian-kutschera** [clawpack/geoclaw#544]
Hi,

I am trying to run `/clawpack_src/clawpack-v5-9-0/geoclaw/examples/tsunami/chile2010`.

However, the file `etopo10min120W60W60S0S.asc` is not generated in `/clawpack_src/clawpack-v5-9-0/geoclaw/scratch/` or misses.

I get the following error:

> make .output
> Makefile:65: warning: overriding recipe for target 'all'
> /import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/clawutil/src/Makefile.common:294: warning: ignoring old recipe for target 'all'
> make data -f Makefile /import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/src/2d/shallow/Makefile.geoclaw /import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/clawutil/src/Makefile.common
> make[1]: Entering directory '/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/examples/tsunami/chile2010'
> Makefile:65: warning: overriding recipe for target 'all'
> /import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/clawutil/src/Makefile.common:294: warning: ignoring old recipe for target 'all'
> rm -f .data
> python setrun.py         geoclaw                  
> Domain:   -120.000000  -60.000000  -60.000000    0.000000
> Level 1 resolution:  dy = 2 deg, 0 min, 0 sec = 222000 meters
> 
> Level 2 resolution:  dy = 1 deg, 0 min, 0 sec = 111000 meters  (refined by 2)
> 
> Level 3 resolution:  dy = 0 deg, 10 min, 0 sec = 18500 meters  (refined by 6)
> 
> Allowing maximum of 3 levels
> Created  Domain.kml
> Region 0: -77.000000  -67.000000  -40.000000  -30.000000
>            minlevel = 3,  maxlevel = 3  t1 = 0.,  t2 = 10000.
> Created  Region_00.kml
> Region 1: -90.000000  -80.000000  -30.000000  -15.000000
>            minlevel = 3,  maxlevel = 3  t1 = 8000.,  t2 = 26000.
> Created  Region_01.kml
> No flagregions found in setrun.py
> Gauge 32412: -86.392, -17.975  
>   t1 = 0.,  t2 = 10000000000.
> Created  gauges.kml
> Traceback (most recent call last):
>   File "/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/examples/tsunami/chile2010/setrun.py", line 433, in <module>
>     kmltools.make_input_data_kmls(rundata)
>   File "/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/src/python/geoclaw/kmltools.py", line 1050, in make_input_data_kmls
>     topo2kml(topo_file_name, topo_type)
>   File "/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/src/python/geoclaw/kmltools.py", line 881, in topo2kml
>     topo.read_header()
>   File "/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/src/python/geoclaw/topotools.py", line 839, in read_header
>     with open(self.path, 'r') as topo_file:
> FileNotFoundError: [Errno 2] No such file or directory: '/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/scratch/etopo10min120W60W60S0S.asc'
> make[1]: *** [/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/clawutil/src/Makefile.common:213: data] Error 1
> make[1]: Leaving directory '/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/geoclaw/examples/tsunami/chile2010'
> make: *** [/import/freenas-m-05-seissol/kutschera/clawpack_src/clawpack-v5-9-0/clawutil/src/Makefile.common:209: .data] Error 2
> 

Do you have any ideas how to fix this?

Best regards
Fabian

**Comment by mandli** [comment]
For that particular example I think you may need to run `make all` to download the file.
