### ISSUE TITLE
Wind Data

### ISSUE THREAD

**Issue by sourabhmet** [clawpack/geoclaw#614]
For now, I am using  default track data provided by Geoclaw community.

Header:
['AL', ' 09', ' 2008090106', '   ', ' BEST', '   0', ' 172N', '  370W', '  30', ' 1006', ' TD', '   0', '    ', '    0', '    0', '    0', '    0', ' 1011', '  250', '  90', '   0', '   0', '   L', '   0', '    ', '   0', '   0', '     INVEST', ' D', ' ']

How do i replace this data with lat lon I have with certiain time interval. 
Please Suggest

**Comment by mandli** [comment]
There are a number of ways to do what you want.  Three of the most straight forward ways are:
1. use the `Storm` class to construct a storm and have it write out in the GeoClaw format,
2. modify the original ATCF data file directly and have GeoClaw deal with it as normal, and
3. directly write a GeoClaw formatted file.

There are references in the documentation for each of these formats and some examples in the [surge-examples](https://github.com/mandli/surge-examples/) repository.

**Comment by sourabhmet** [comment]
I have downloaded the data from ATCF for harvey event.
And after running it, what I am getting is in the image below. In the image xlabel and ylabel is correctly mentioned but the region is tilted. Any suggestion ?

On top of it , Its not printing a track and other filed including storm surge  

![frame0000fig1002](https://github.com/clawpack/geoclaw/assets/50980051/fbded33b-5d4f-4d1a-a4d2-88dd9192b79e)

**Comment by mandli** [comment]
The topography data is clearly flipped.  Is this from a geoTIFF?

The relative dates of the storm are important so how the `time_offset` value is set relative to the storm controls how the simulation time matches with the storm file.  GeoClaw only keeps track of the seconds relative to `time_offset` and depends on this setting to translate the storm's time frame into this window.

**Comment by sourabhmet** [comment]
Thanks Mandli,

I downloaded this data in netcdf form and converted to Arcgis Ascii
(similar as Geoclaw ) format.

Initially it was working fine but after changing the Track file it flipped.



*Regards*

*Sourabh Shrivastava, PhD*

**Comment by mandli** [comment]
The track file should not have impacted the topography but using a netcdf file could do that if the coordinates got flipped when converted.
