### ISSUE TITLE
Significant Wave Height

### ISSUE THREAD

**Issue by sourabhmet** [clawpack/geoclaw#619]
Hi,

Please help me out to calculate the significant wave height.
Is there any specific command in the model ?

On top of it I have 1000 locations for which I want to extract the surge height and significant wave height.

However, I failed to store the data in fix_grid and sve it into a NetCDF file.

**Comment by mandli** [comment]
What are you defining as the significant wave height?  If you are looking for the statistical definition and are just interested in the long-wave component you will have to do that with what GeoClaw outputs.  If you are interested in the short wave-length waves, commonly in reference to wind generated waves, then GeoClaw does not have the capability to do this.  We have used/developed a few models that do this [1, 2] but they are currently unavailable as a component of GeoClaw.

For the locations, if you are looking for the time dependent surge height and they are not on a grid aligned with the coordinate axes, then gauges are the best tool for the job (http://www.clawpack.org/gauges.html).  Alternatively, if you wanted maximum height then you could use some of the fixed grid monitoring functions (https://www.clawpack.org/fgmax.html).  Sticking the output of either of these into a NetCDF file then should be relatively straight forward with any number of tools in Python for instance.

[1]C.J. Conroy, K.T. Mandli, E.J. Kubatko, Numerical Considerations for Quantifying Air–Water Turbulence with Moment Field Equations, Water Waves 3 (2021) 319–354. https://doi.org/10.1007/s42286-021-00048-y.

[2]C.J. Conroy, E.J. Kubatko, A. Nappi, R. Sebian, D. West, K.T. Mandli, hp discontinuous Galerkin methods for parametric, wind-driven water wave models, Adv. Water Resour. 119 (2018) 70–83. https://doi.org/10.1016/j.advwatres.2018.04.008.

Kyle

**Comment by sourabhmet** [comment]
Thanks Mandli,

Can you provide any example file (Setrun.py), where the fixgrid is set and the data is converted to netcdf ?

It will be helpful, as I am trying many times but couldnt get any sucess.

**Comment by mandli** [comment]
There is an [example](https://github.com/clawpack/geoclaw/tree/master/examples/tsunami/chile2010_fgmax-fgout) of how to use fixed grids that should be helpful.  The NetCDF part is more specific to what you would like to do so I would suggest looking at examples of reading and writing NetCDF files with something like [xarray](https://docs.xarray.dev/en/stable/index.html) to get an idea of how to do that.
