### ISSUE TITLE
Undefined names in storm.py

### ISSUE THREAD

**Issue by bolliger32** [clawpack/geoclaw#623]
My linter is noticing that `seconds2date` and `fileWrite` seem to be undefined in `storm.py`. Did these used to be defined somewhere? I don't think these get used often but it looks like it will affect `write_atcf`, `write_hurdat`, `write_jma`, and `make_multi_structure`, which isn't actually called anywhere.

**Comment by mandli** [comment]
What branch/version are you on?  A linter is now going to be run on PRs but the changes that fix some failures has not been merged yet (#610).  There was some things in there that needed to be commented out as they did not work consistently and had some cruft buildup.

**Comment by bolliger32** [comment]
@mandli you're right I was looking at master and didn't see #610, which I think fixes this.

**Comment by mandli** [comment]
There are a number of things that needed to be fixed.  Hopefully we can get the testing up and running sooner rather than later.
